version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9094:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:7.9.2
  #   mem_limit: 1g
  #   volumes:
  #     - "./config/filebeat.yml:/usr/share/filebeat/filebeat.yml"
  #     # - "/var/lib/docker/containers:/var/lib/docker/containers"
  #   links:
  #     - kafka
  #   depends_on:
  #     - kafka