filebeat.config:
modules: 
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
  - add_docker_metadata: ~

output.kafka:
    hosts: ["10.3.133.190:9092"]
    topic: 'KUclap-logs'
    partition.round_robin:
      reachable_only: false

    compression: gzip
    max_retries: 2
    max_message_bytes: 1000000
