name: Deploy-filebeat-to-Gandalf

on:
  push:
    branches:
      - release-gandalf

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Filebeat - Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: kuclap/server-conf-filebeat/kuclap-gandalf-filebeat
          registry: docker.pkg.github.com
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./docker/Filebeat.Dockerfile
          tags: "0.0.0, latest"
      - name: Deploy package to digitalocean
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ secrets.GIT_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.DO_GANDALF_HOST }}
          username: ${{ secrets.DO_GANDALF_USERNAME }}
          password: ${{ secrets.DO_GANDALF_PASSWORD }}
          port: ${{ secrets.DO_GANDALF_PORT }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN
          script: |
            docker stop kuclap-gandalf-filebeat
            docker container prune -f 
            docker image prune -f
            docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker pull docker.pkg.github.com/kuclap/server-conf-filebeat/kuclap-gandalf-filebeat:latest
            docker run --name kuclap-gandalf-filebeat --network=kuclap --restart=always -v /var/lib/docker/containers:/usr/share/dockerlogs/data:ro -v ./mock-logs:/usr/share/filebeat/mock-logs -v /var/run/docker.sock:/var/run/docker.sock  -dit docker.pkg.github.com/kuclap/server-conf-filebeat/kuclap-gandalf-filebeat:latest
